language: ruby

before_script:
  - chmod +x ./script/cibuild

script:
  - ./script/cibuild

branches:
  only:
    - gh-pages
    - /pages-(.*)

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
