# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CLIR Publication Metadata
email: contact@clir.org
description:  CLIR Publication Metadata
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://metadata.clir.org/" # the base hostname & protocol for your site
twitter_username: clirdlf
github_username:  clirdlf

exclude: ['.gitignore', '.env', '.git', 'node_modules', 'temp', 'vendor', 'gulpfile.js', 'package*.json', 'README.md', '*.rb']
sass:
  style: compressed

markdown: kramdown

google-analytics: ''

defaults:
  - scope:
      path: "metadata"
    values:
      metadata: true
